version: '3.4'

volumes:
  jenkins_data:

services:
  jenkins:
    container_name: jenkins
    image: niiiiiiiice/jenkins-inbound-agent-docker:1.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - jenkins_data:/var/jenkins_home
      - /usr/local/jenkins-conf:/usr/local/jenkins-conf
      - /var/run/docker.sock:/var/run/docker.sock